## 属性
* `ndim`：维度
* `shape`：行数和列数
* `size`：元素个数
         
## 创建
* `array`：创建数组
* `dtype`：指定数据类型
* `zeros`：创建数据全为 0
* `ones`：创建数据全为 1
* `empty`：创建数据无意义
* `arange`：按指定范围创建数据
* `linspace`：创建线段
* `vsplit & hsplit`：切割数组

In [1]:
import numpy as np

### 1. 创建数组 array

In [2]:
array = np.array([2, 23, 4])
print(array)

[ 2 23  4]


In [3]:
array = np.array([[2, 23, 4], [2, 32, 4]])
print(array)

[[ 2 23  4]
 [ 2 32  4]]


### 2. Numpy 的一些属性

In [4]:
print('number of dim', array.ndim) # 维度：ndim

number of dim 2


In [5]:
print('shape:', array.shape) # 行数和列数：shape

shape: (2, 3)


In [6]:
print('size:', array.size) # 元素个数：size

size: 6


### 3. 指定数据类型 dtype

In [7]:
array = np.array([2, 23, 4], dtype = np.int)
print(array)
print(array.dtype)
array = np.array([2, 23, 4], dtype = np.float)
print(array)
print(array.dtype)

[ 2 23  4]
int32
[ 2. 23.  4.]
float64


### 4. zeros、ones、empty 创建数组

默认情况下，`ones` 函数创建的类型为**浮点型**，要创建其他类型，使用 dtype 来进行修改。

`empty` 创建的数组中，包含的均是无意义的数值。

In [8]:
array_zeros = np.zeros((3,4))
print(array_zeros)

array_ones = np.ones((3,4))
print(array_ones)
print(array_ones.dtype) 

array_empty = np.empty((3,4))
print(array_empty)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 5. arange 创建数组

In [9]:
array_arange = np.arange(12)
print(array_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [10]:
array_arange = np.arange(12).reshape((3,4))
print(array_arange)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
array_arange = np.arange(10, 20, 2) # 10-19 的数据，2 步长
print(array_arange)

[10 12 14 16 18]


### 6. linspace 生成线段

In [12]:
array_linspace = np.linspace(1, 10, 20) # 从 1 到 10，分成 20 段，自动匹配步长
print(array_linspace)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [13]:
array_linspace = np.linspace(1, 10, 20).reshape((5, 4))
print(array_linspace)

[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


### 7. 切割 vsplit 和 hsplit
vsplit 进行分行
hsplit 进行分列

In [14]:
array_split = np.arange(18).reshape(-1, 3)
print(array_split)

print(np.vsplit(array_split, 3)) # 分三行

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]


In [15]:
print(np.vsplit(array_split, [1, 5])) # 从第 1 行到第 4 行分行

[array([[0, 1, 2]]), array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]]), array([[15, 16, 17]])]
