In [1]:
import numpy as np

a = np.array([10, 20, 30, 40])
print(a)
b = np.arange(4)
print(b)

[10 20 30 40]
[0 1 2 3]


### 1. 四则运算

In [2]:
c = a - b
print(c)

c = a + b
print(c)

c = a * b
print(c)

c = a / (b+1)
print(c)

[10 19 28 37]
[10 21 32 43]
[  0  20  60 120]
[10. 10. 10. 10.]


### 2. 开根号 & 指数 & 平方 & n次幂

In [3]:
c = np.sqrt(b) # 开根号
print(c)

c = np.exp(b) # 指数
print(c)

c = np.square(b) # 平方
print(c)

c = np.power(b, 2) # n次幂(第二项可以是数字也可以是数组，但列数要相同)
print(c)

c = b ** 2 # 平方
print(c)

[0.         1.         1.41421356 1.73205081]
[ 1.          2.71828183  7.3890561  20.08553692]
[0 1 4 9]
[0 1 4 9]
[0 1 4 9]


### 3. 求和 & 最大值 & 最小值（axis）

In [4]:
d = np.arange(3,15).reshape((3, 4))
print(d)

print(np.sum(d))
print(np.max(d))
print(np.min(d))
print(np.sum(d, axis=1)) #axis=1 表示行，这里对每一行求和
print(np.min(d, axis=0)) #axis=0 表示列，这里在每列中找出最小值
print(np.min(d, axis=1))

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
102
14
3
[18 34 50]
[3 4 5 6]
[ 3  7 11]


### 4. 数组的均值 & 中位数 & 累加 & 累差

In [5]:
print(d)
# 均值
print(np.mean(d))
print(np.mean(d, axis=0)) # 对列求均值
print(np.mean(d, axis=1)) # 对行求均值
print(d.mean())
print(np.average(d))
# 中位数
print(np.median(d))
#累加
print(np.cumsum(d))
#累差
print(np.diff(d))

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
8.5
[ 7.  8.  9. 10.]
[ 4.5  8.5 12.5]
8.5
8.5
8.5
[  3   7  12  18  25  33  42  52  63  75  88 102]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


### 5. 数组排序

In [6]:
e = np.arange(14, 2, -1).reshape((3,4))
print(e)

print(np.sort(e)) #逐行排序

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


### 6. 数组取值
浅拷贝：直接赋值，两者对应同一块内存地址
       
深拷贝：np.copy

In [7]:
f = np.array([[1, 2], [3, 4]])
print(f)
g = f # 浅拷贝
h = f.copy() # 深拷贝 np.copy(f)
print(f[1,1], f[1][1])
g[1][1] = 5
print(f[1][1], g[1][1], h[1][1])

[[1 2]
 [3 4]]
4 4
5 5 4


### 7. 数组合并
hstack：横向拼接
    
vstack：纵向拼接

In [8]:
print(np.hstack([f,g]))

[[1 2 1 2]
 [3 5 3 5]]


In [9]:
print(np.vstack([f,h]))

[[1 2]
 [3 5]
 [1 2]
 [3 4]]


np.newsxis() 增加维度

In [10]:
i = np.arange(3, 15)
print(i)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [11]:
print(i[np.newaxis,:])
print(i[np.newaxis,:].shape)

[[ 3  4  5  6  7  8  9 10 11 12 13 14]]
(1, 12)


In [12]:
print(i[:,np.newaxis])
print(i[:,np.newaxis].shape)

[[ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]
(12, 1)


**np.concatenate()**
       
当你的合并操作需要针对多个矩阵或序列时，借助 `concatenate` 函数可能会让你使用起来比前述的函数更加方便：

In [13]:
j = np.array([1,1,1])[:,np.newaxis]
print(j)
k = np.array([2,2,2])[:,np.newaxis]
print(k)

[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]


In [14]:
jk0 = np.concatenate((j,k,k,j), axis=0)
print(jk0)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]


In [15]:
jk1 = np.concatenate((j,k,k,j), axis=1)
print(jk1)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


### 8. 索引

In [16]:
print(i[3])

6


In [17]:
i = np.arange(3, 15).reshape((3, 4))
print(i)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [18]:
print(i[2])

[11 12 13 14]


In [19]:
print(i[1][1])
print(i[1, 1])
print(i[1, 1:3])

8
8
[8 9]


In [20]:
for row in i:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [30]:
for column in np.transpose(i): # 对 i 进行转置
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [22]:
print(i.flatten()) # flatten 展开性质的函数

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [23]:
for item in i.flat: # flat 是一个迭代器，本身是一个 object 属性
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


### 9. 数组切割

In [24]:
l = np.arange(12).reshape((3, 4))
print(l)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
print(np.split(l, 2, axis=1)) # 纵向切2

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [26]:
print(np.split(l, 3, axis=0)) # 横向切3

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [27]:
print(np.array_split(l, 3, axis=1)) # 不等量切割

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [28]:
print(np.vsplit(l, 3)) # 等于 print(np.split(A, 3, axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [29]:
print(np.hsplit(l, 2))# 等于 print(np.split(A, 2, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
